config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root to: 'articles#index'

  resources :articles, only: [:show, :new, :create, :edit, :update, :destroy]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        if @article.save # 保存したら、その作成したページに飛ぶ
            redirect_to article_path(@article), notice: '保存できたよ'
        else # 保存されなかった時、フォームを再表示
            flash.now[:error] = '保存に失敗しました'
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to article_path(@article), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        article = Article.find(params[:id])
        article.destroy!
        redirect_to root_path, status: :see_other, notice: '削除に成功しました'
    end

    private
    def article_params
        params.require(:article).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<div class="container">
    <ul>
        <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
    <%= form_with(model: @article, url: article_path(@article), method: 'put', local: true) do |f| %>
        <div>
            <%= f.label :title, 'タイトル' %>
        </div>
        <div>
            <%= f.text_field :title, class: 'text' %>
        </div>
        <div>
            <%= f.label :content, '内容' %>
        </div>
        <div>
            <%= f.text_area :content %>
        </div>
        <%= f.submit '保存', class: 'btn-primary' %>
    <% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="tabs">
    <div class="tabs_item active">
      新着記事一覧
    </div>
    <div class="tabs_item">
      タイムライン
    </div>
  </div>

  <% @articles.each do |article| %>
    <%= link_to article_path(article) do %>
      <div class="card">
        <div class="card_image">
          <%= image_tag 'eyecatch1.png' %>
        </div>
        <div class="card_content">
          <div class="card_title">
            <%= article.title %>
          </div>
          <div class="card_heart">
            <%= image_tag 'heart.svg' %>
            <span>23</span>
          </div>
          <div class="card_detail">
            <%= image_tag 'default-avatar.png' %>
            <div>
              <p>cohki0305</p>
              <p>2020/4/16</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= link_to new_article_path do %>
    <div class="float_btn">
      <i class="fa fa-plus"></i>
    </div>
  <% end %>

</div>

app/views/articles/new.html.erb
<div class="container">
    <ul>
        <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
    <%= form_with(model: @article, url: articles_path, method: 'post', local: true) do |f| %>
        <div>
            <%= f.label :title, 'タイトル' %>
        </div>
        <div>
            <%= f.text_field :title, class: 'text' %>
        </div>
        <div>
            <%= f.label :content, '内容' %>
        </div>
        <div>
            <%= f.text_area :content %>
        </div>
        <%= f.submit '保存', class: 'btn-primary' %>
    <% end %>
</div>

app/views/articles/show.html.erb
<div class="article">
    <h1 class="article_title"><%= @article.title %></h1>
    <div class="article_detail">
        <%= image_tag 'default-avatar.png' %>
        <div>
            <p>cohki0305</p>
            <p>2020/04/16</p>
        </div>
        <div class="article_detail_actions">
            <div class="dropdown">
                <%= image_tag 'actions.svg', class: 'dropbtn' %>
                <div class="dropdown-content mini">
                    <%= link_to '編集する', edit_article_path(@article) %>
                    <%= link_to '削除する', article_path(@article), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' } %>
                </div>
            </div>
        </div>
    </div>
    <div class="article_content">
        <%= @article.content %>
    </div>
    <div class="article_heart">
        <%= image_tag 'heart.svg' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Aym Blog App" %></title>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <p class="header_pageTitle">新着記事</p>
      <div class="dropdown">
        <%= image_tag 'default-avatar.png', class: 'header_avatar dropbtn' %>
        <div class="dropdown-content">
          <a href="#">プロフィール</a>
          <a href="#">ログアウト</a>
        </div>
      </div>
    </header>
    <% if flash.present? %>
      <div class="flash">
        <% flash.each do |key, value| %>
          <div class="<%= key %>"><%= value %></div>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>